name: Auto Fix Vulnerabilities

on:
  workflow_run:
    workflows: ["Generate Snyk Summary"]
    types:
      - completed

jobs:
  fix:
    runs-on: ubuntu-latest

    env:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download summary
        uses: actions/download-artifact@v4
        with:
          name: snyk-summary
          path: scripts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Mistral Fix and Create PR
        run: |
          pip install requests PyGithub
          python scripts/pom_fix_from_report.py scripts/snyk-summary.txt
